version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80" # Map port 80 on the host to port 80 in the container
    environment:
      - NODE_ENV=production